main:main.c LST_TIMER.h block_queue.h threadpool.h http_conn.cpp http_conn.h connection_pool.h connection_pool.cpp log.h log.cpp
	g++ -o server main.c LST_TIMER.h block_queue.h threadpool.h http_conn.cpp http_conn.h connection_pool.h connection_pool.cpp log.h log.cpp -lpthread -lmysqlclient
clean:
	rm -rf *.o *.h.gch	



